; Program ini menghitung luas Persegi Panjang
; Dengan dua masukan input variabel bebas alas dan tinggi dapat bernilai (+) atau (-)
; Output luas sebagai variabel yang terikat

INCLUDE 'emu8086.inc'
#MAKE_COM#
ORG 100H
JMP MULAI
PSN1    DB "HITUNG LUAS PERSEGI PANJANG DENGAN INPUT VARIABEL ALAS DAN TINGGI", 13,10
        DB "OUTPUT LUAS HASIL KALI VARIABEL ALAS DENGAN TINGGI",13,10,13,10,'$'
PSN2    DB "MASUKKAN NILAI PANJANG PERSEGI PANJANG : $"
PSN3    DB "MASUKKAN NILAI LEBAR PERSEGI PANJANG : $"
PSN4    DB "LUAS PERSEGI PANJANG ADALAH : $"
PSN5    DB 13,10,13,10,"TERIMA KASIH TELAH MENGGUNAKAN PROGRAM INI!"
        DB 13,10,13,10,"TEKAN SEMBARANG UNTUK KELUAR $"
PANJANG DW ?
LEBAR   DW ?
BG      DW ?
ARE     DW ?

MULAI:
LEA DX,PSN1
MOV AH,9
INT 21H

LEA DX,PSN2
MOV AH,9
INT 21H

CALL SCAN_NUM

MOV PANJANG,CX

PUTC 13
PUTC 10

LEA DX,PSN3
MOV AH,9
INT 21H

CALL SCAN_NUM

MOV LEBAR,CX

MOV AX,PANJANG
MOV BX,LEBAR
IMUL BX
DIV BX
PUSH AX

PUTC 13
PUTC 10

LEA DX,PSN4
MOV AH,9
INT 21H

POP AX
MOV ARE,AX

CALL PRINT_NUM

PUTC 13
PUTC 10

LEA DX,PSN5
MOV AH,9
INT 21H

MOV AH,0
INT 16H

RET

DEFINE_SCAN_NUM
DEFINE_PRINT_NUM
DEFINE_PRINT_NUM_UNS
END
